### ISSUE TITLE
What about cron-like tasks definition?

### ISSUE THREAD

**Issue by cusspvz** [neoziro/node-taskman#23]
We are using `taskman` for support tasks on top of workers.

I don't feel safe with some kind of manual triggering for cron-like tasks from within our offices.

Had you ever think about placing some kind of mechanism for this kind of jobs?

**Comment by neoziro** [comment]
@cusspvz I am sorry but I don't understand, taskman is designed to run a worker in background. Tasks are taken as soon as a new task is published.

**Comment by cusspvz** [comment]
@neoziro thanks for your answer! :)

*taskman* does its job flawless, by executing pontual tasks. My question is: Have you ever think to support schedule tasks on `taskman`?

**Comment by neoziro** [comment]
@cusspvz ah OK, no I do not plan to add this support to taskman, sorry.

**Comment by cusspvz** [comment]
Thanks anyway!!

Also thanks for providing *taskman* as open-source, you did a great job!! :)
